# Global
backbone: tfgridnet_5l32c100 # ncsnpp_v2_5M, tfgridnet_5l32c100
sde: sbve  # ouve, sbve
# noise_schedule: bb
sampler_type: ode
N: 5

# Log
version: Bridge_Path=sbve_Backbone=${backbone}_Loss=hybrid
log_dir: #! Enter your log path
save_ckpt_interval: 50000
nolog: false
logger: tensorboard  # Or wandb
wandb_name: null

# Train
ckpt: null  # For resuming
max_epochs: -1
lr: 1e-4
num_eval_files: 100
loss_type: data_prediction_hybrid  # score_matching, data_prediction
l1_weight: 0.001
pesq_weight: 0.0
sr: 16000

scheduler_config:
  scheduler: warmup  # fixed, warmup
  config:
    warmup_steps: 40000
    decay_until_step: 400000
    max_lr: 5e-4
    min_lr: 5e-6

# Data
base_dir: #! Enter your data path
format: default
batch_size: 4 # Batch size per GPU
n_fft: 512
hop_length: 256
num_frames: 250
window: sqrthann
num_workers: 6
num_data_per_epoch: null  # 80000
dummy: false
normalize: noisy
transform_type: exponent
